development:
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  host: localhost
  username: postgres
  password: vaibhavgeek   

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  username: postgres
  password: vaibhavgeek

production:
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  username: postgres
  password: vaibhavgeek

cucumber:
  <<: *TEST