development:
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  host: localhost
  username: Dell-pc
  password: rainbow   

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  username: Dell-pc
  password: rainbow

production:
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  username: vaibhav
  password: nonsense

cucumber:
  <<: *TEST