development:
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  username: vaibhavgeek
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: edunova
  pool: 5
  username: vaibhavgeek
  password:

production:
  production:
  adapter: mysql2
  encoding: utf8
  database: edunova
  username: vaibhavgeek 
  password: F1inindia
  host: aafgkrl4000vuv.cldiuzwqkq5z.us-east-1.rds.amazonaws.com
  port: 3306

cucumber:
  <<: *TEST